spring:
  application:
    name: backend


  datasource:
    url: jdbc:h2:mem:bookdb
    driver-class-name: org.h2.Driver
    username: sa
    password:


  h2:
    console:
      enabled: true


  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true


server:
  port: 8080